---
version: "3"
services:
 devopsdb:
   image: bijje/newapp:dbimage
   ports:
     - "3306:3306"

 application:
   image: bijje/newapp:appimage
   container_name: containerapp
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
